/**
 * Level Definitions - 50 levels per domain
 * Evidence-based cognitive progression using:
 * - Bloom's Taxonomy (knowledge → comprehension → application)
 * - Zone of Proximal Development (scaffolded learning)
 * - Spaced Repetition principles
 */

export interface LevelDefinition {
  levelNumber: number;
  title: string;
  description: string;
  learningObjectives: string[];
  pedagogicalApproach: string;
  difficulty: "easy" | "medium" | "hard";
  estimatedDuration: number; // minutes
  bloomsLevel: "remember" | "understand" | "apply" | "analyze" | "evaluate" | "create";
  contentGuide: string;
}

export interface DomainLevelMap {
  language: LevelDefinition[];
  mathematics: LevelDefinition[];
  logical: LevelDefinition[];
}

/**
 * LANGUAGE DOMAIN - 50 Levels
 * Progression: Phonemic awareness → Phonics → Vocabulary → Reading → Comprehension
 * Aligned with: Reading Recovery, Fountas & Pinnell, Wilson Reading Framework
 */
export const LanguageLevels: LevelDefinition[] = [
  // PHASE 1: Phonemic Awareness (Levels 1-5)
  {
    levelNumber: 1,
    title: "Letter Sounds: A-E",
    description: "Recognize and name letters A through E with audio pronunciation",
    learningObjectives: ["Identify individual letter sounds", "Develop phonemic awareness"],
    pedagogicalApproach: "Multisensory: visual + auditory + kinesthetic",
    difficulty: "easy",
    estimatedDuration: 5,
    bloomsLevel: "remember",
    contentGuide: "Use clear, distinct letters with color coding. Include animal associations (Apple-Ant, Egg-Elephant)",
  },
  {
    levelNumber: 2,
    title: "Letter Sounds: F-J",
    description: "Master sounds for F, G, H, I, J with object associations",
    learningObjectives: ["Expand letter-sound correspondence", "Build automaticity"],
    pedagogicalApproach: "Scaffolded learning with visual cues",
    difficulty: "easy",
    estimatedDuration: 5,
    bloomsLevel: "remember",
    contentGuide: "Use consistent visual format. Strong/weak sounds (C hard/soft).",
  },
  {
    levelNumber: 3,
    title: "Letter Sounds: K-O",
    description: "Continue letter recognition K through O with mixed activities",
    learningObjectives: ["Complete initial consonant recognition", "Introduce vowels"],
    pedagogicalApproach: "Mixed modality (visual, auditory, kinesthetic drawing)",
    difficulty: "easy",
    estimatedDuration: 6,
    bloomsLevel: "remember",
    contentGuide: "Start vowel emphasis. Use keyboard highlighting for tactile feedback.",
  },
  {
    levelNumber: 4,
    title: "Letter Sounds: P-T",
    description: "Learn consonant clusters and complex sounds P-T",
    learningObjectives: ["Recognize consonant blends", "Develop letter-sound automaticity"],
    pedagogicalApproach: "Repetition with pattern recognition",
    difficulty: "easy",
    estimatedDuration: 6,
    bloomsLevel: "remember",
    contentGuide: "Minimal pairs practice (pat/bat, tap/cap). Include frequency analysis.",
  },
  {
    levelNumber: 5,
    title: "Complete Alphabet Challenge",
    description: "Full alphabet review with speed and accuracy challenge",
    learningObjectives: ["Master all 26 letters", "Achieve automaticity"],
    pedagogicalApproach: "Gamified repetition with feedback",
    difficulty: "medium",
    estimatedDuration: 8,
    bloomsLevel: "remember",
    contentGuide: "Timed alphabet matching. Visual + auditory reinforcement. 90% accuracy target.",
  },

  // PHASE 2: Phonics & Simple Words (Levels 6-15)
  {
    levelNumber: 6,
    title: "CVC Words: Short A",
    description: "Blend sounds into simple CVC words with short 'a' vowel",
    learningObjectives: ["Blend individual sounds into words", "Recognize short vowel sounds"],
    pedagogicalApproach: "Sound blending (segmentation → blending)",
    difficulty: "easy",
    estimatedDuration: 7,
    bloomsLevel: "understand",
    contentGuide: "CVC pattern: cat, bat, rat, hat, mat, sat. Use consistent order.",
  },
  {
    levelNumber: 7,
    title: "CVC Words: Short E, I",
    description: "Master short E and I vowel CVC words",
    learningObjectives: ["Distinguish short vowel sounds", "Build decoding automaticity"],
    pedagogicalApproach: "Contrastive analysis (sound pairs)",
    difficulty: "easy",
    estimatedDuration: 7,
    bloomsLevel: "understand",
    contentGuide: "Minimal pairs: pet/pit, bed/bid, hen/him. Auditory discrimination practice.",
  },
  {
    levelNumber: 8,
    title: "CVC Words: Short O, U",
    description: "Complete CVC mastery with short O and U sounds",
    learningObjectives: ["Master all short vowel CVC patterns", "Develop fluency"],
    pedagogicalApproach: "Systematic phonics with full vowel coverage",
    difficulty: "easy",
    estimatedDuration: 7,
    bloomsLevel: "understand",
    contentGuide: "Words: pot, dot, hot, rug, bug, hug. Mixed vowel review.",
  },
  {
    levelNumber: 9,
    title: "Word Families: -at, -og, -un",
    description: "Recognize word families and rhyming patterns",
    learningObjectives: ["Understand onset-rime structure", "Build decoding flexibility"],
    pedagogicalApproach: "Word family chunking strategy",
    difficulty: "medium",
    estimatedDuration: 8,
    bloomsLevel: "understand",
    contentGuide: "Families: -at (cat, bat, rat, hat), -og (dog, log, fog), -un (run, sun, bun, gun)",
  },
  {
    levelNumber: 10,
    title: "Consonant Blends: bl, cl, st",
    description: "Introduce initial consonant blends in simple words",
    learningObjectives: ["Blend consonant clusters", "Expand word variety"],
    pedagogicalApproach: "Explicit blend instruction",
    difficulty: "medium",
    estimatedDuration: 8,
    bloomsLevel: "understand",
    contentGuide: "Words: blue, black, clock, list, stop. Focus on clear articulation.",
  },
  {
    levelNumber: 11,
    title: "Digraphs: ch, sh, th",
    description: "Learn consonant digraphs that make single sounds",
    learningObjectives: ["Recognize digraph patterns", "Expand phonetic knowledge"],
    pedagogicalApproach: "Pattern recognition with mouth position awareness",
    difficulty: "medium",
    estimatedDuration: 9,
    bloomsLevel: "understand",
    contentGuide: "Words: chin, chat, share, ship, think, that. Include mouth/tongue position hints.",
  },
  {
    levelNumber: 12,
    title: "Silent E Pattern",
    description: "Understand silent E and vowel lengthening",
    learningObjectives: ["Learn silent E rule", "Decode long vowel words"],
    pedagogicalApproach: "Rule-based pattern learning",
    difficulty: "medium",
    estimatedDuration: 9,
    bloomsLevel: "understand",
    contentGuide: "Pairs: cap→cape, bit→bite, not→note. Visual transformation.",
  },
  {
    levelNumber: 13,
    title: "Long Vowel Teams: ai, oa, ee",
    description: "Learn vowel combinations that make long sounds",
    learningObjectives: ["Recognize vowel digraphs", "Expand decoding strategies"],
    pedagogicalApproach: "Team-based approach to vowel sounds",
    difficulty: "medium",
    estimatedDuration: 9,
    bloomsLevel: "understand",
    contentGuide: "Words: sail, boat, tree. Include 'helper vowel' concept explanation.",
  },
  {
    levelNumber: 14,
    title: "Ending Patterns: -ing, -ed, -er",
    description: "Master common morpheme endings",
    learningObjectives: ["Recognize common suffixes", "Build morphological awareness"],
    pedagogicalApproach: "Morpheme-based instruction",
    difficulty: "medium",
    estimatedDuration: 10,
    bloomsLevel: "understand",
    contentGuide: "Words: running, jumped, teacher. Show root+ending segmentation.",
  },
  {
    levelNumber: 15,
    title: "Word Reading Fluency Challenge",
    description: "Read varied word list with increasing complexity",
    learningObjectives: ["Achieve reading fluency", "Apply phonetic knowledge"],
    pedagogicalApproach: "Fluency practice with timed word recognition",
    difficulty: "hard",
    estimatedDuration: 12,
    bloomsLevel: "apply",
    contentGuide: "Mixed CVC, blends, digraphs, silent E words. Target 40+ wpm.",
  },

  // PHASE 3: Sentence & Simple Reading (Levels 16-30)
  {
    levelNumber: 16,
    title: "Sight Words: The, A, And",
    description: "Learn high-frequency sight words (Dolch Primer List)",
    learningObjectives: ["Recognize sight words automatically", "Build reading speed"],
    pedagogicalApproach: "Whole-word memorization with multi-modal practice",
    difficulty: "medium",
    estimatedDuration: 10,
    bloomsLevel: "remember",
    contentGuide: "Dolch top 10 words. Use flashcard approach with varied contexts.",
  },
  {
    levelNumber: 17,
    title: "Sight Words: He, She, It, Was",
    description: "Expand sight word recognition with function words",
    learningObjectives: ["Master pronoun sight words", "Enable sentence reading"],
    pedagogicalApproach: "Contextual repetition in sentences",
    difficulty: "medium",
    estimatedDuration: 10,
    bloomsLevel: "remember",
    contentGuide: "Personal pronouns and past tense. Use color coding for categories.",
  },
  {
    levelNumber: 18,
    title: "Simple Sentences: Subject Action Object",
    description: "Read simple SVO sentence structure",
    learningObjectives: ["Decode simple sentences", "Begin comprehension"],
    pedagogicalApproach: "Sentence structure scaffolding (SVO pattern)",
    difficulty: "medium",
    estimatedDuration: 12,
    bloomsLevel: "understand",
    contentGuide: "Sentences: 'The cat sat. He is happy.' Use visual supports.",
  },
  {
    levelNumber: 19,
    title: "Simple Question Words: Who, What, Where",
    description: "Comprehend and respond to question words",
    learningObjectives: ["Understand question formation", "Answer simple questions"],
    pedagogicalApproach: "Interrogative word patterns with visual support",
    difficulty: "medium",
    estimatedDuration: 12,
    bloomsLevel: "understand",
    contentGuide: "Questions: 'Who is running? What is it? Where is the dog?'",
  },
  {
    levelNumber: 20,
    title: "Picture-Text Matching",
    description: "Match simple sentences to corresponding images",
    learningObjectives: ["Build semantic connections", "Develop visual-linguistic processing"],
    pedagogicalApproach: "Visual scaffold with gradual reduction",
    difficulty: "medium",
    estimatedDuration: 10,
    bloomsLevel: "understand",
    contentGuide: "4-choice matching. Use varied contexts and objects.",
  },
  {
    levelNumber: 21,
    title: "Story: The Hungry Cat (4 sentences)",
    description: "Read and comprehend short narrative",
    learningObjectives: ["Build narrative comprehension", "Infer basic plot"],
    pedagogicalApproach: "Scaffolded story reading with pictures",
    difficulty: "medium",
    estimatedDuration: 12,
    bloomsLevel: "understand",
    contentGuide: "4-sentence story. After each sentence, show supporting image.",
  },
  {
    levelNumber: 22,
    title: "Reading Comprehension: Prediction",
    description: "Predict what happens next in a simple story",
    learningObjectives: ["Develop prediction strategy", "Engage active comprehension"],
    pedagogicalApproach: "Prediction with sentence completion",
    difficulty: "medium",
    estimatedDuration: 12,
    bloomsLevel: "apply",
    contentGuide: "Story excerpts. Before revealing next sentence, ask prediction.",
  },
  {
    levelNumber: 23,
    title: "Reading Comprehension: Recall",
    description: "Answer questions about read text",
    learningObjectives: ["Recall explicit details", "Demonstrate literal comprehension"],
    pedagogicalApproach: "Question-answering with multiple choice",
    difficulty: "medium",
    estimatedDuration: 13,
    bloomsLevel: "understand",
    contentGuide: "Factual questions about read story. Reference text remains visible.",
  },
  {
    levelNumber: 24,
    title: "Reading Comprehension: Inference",
    description: "Draw simple inferences from text clues",
    learningObjectives: ["Make text-based inferences", "Build deeper comprehension"],
    pedagogicalApproach: "Scaffolded inference from explicit clues",
    difficulty: "hard",
    estimatedDuration: 14,
    bloomsLevel: "apply",
    contentGuide: "Questions require simple inference. Provide thinking stems.",
  },
  {
    levelNumber: 25,
    title: "Sequencing: Story Order",
    description: "Arrange story sentences in correct order",
    learningObjectives: ["Understand temporal sequence", "Build narrative structure"],
    pedagogicalApproach: "Sequencing with logical progression",
    difficulty: "hard",
    estimatedDuration: 13,
    bloomsLevel: "apply",
    contentGuide: "4 event sentences to sequence. Include temporal markers (First, Then, Finally).",
  },
  {
    levelNumber: 26,
    title: "Vocabulary in Context: Basic",
    description: "Learn word meanings from sentence context",
    learningObjectives: ["Use context clues", "Expand vocabulary through reading"],
    pedagogicalApproach: "Contextual word learning",
    difficulty: "medium",
    estimatedDuration: 12,
    bloomsLevel: "understand",
    contentGuide: "New words in supportive context. Dictionary definition provided.",
  },
  {
    levelNumber: 27,
    title: "Instructions: Simple Steps",
    description: "Read and follow 2-3 step written instructions",
    learningObjectives: ["Understand procedural text", "Follow instructions accurately"],
    pedagogicalApproach: "Step-by-step instruction following",
    difficulty: "medium",
    estimatedDuration: 12,
    bloomsLevel: "apply",
    contentGuide: "Simple recipes or craft instructions. Checkboxes for each step.",
  },
  {
    levelNumber: 28,
    title: "Beginning-Middle-End",
    description: "Identify story structure components",
    learningObjectives: ["Understand narrative structure", "Organize story elements"],
    pedagogicalApproach: "Explicit story structure instruction",
    difficulty: "medium",
    estimatedDuration: 13,
    bloomsLevel: "understand",
    contentGuide: "Label three parts of simple story. Use graphic organizer.",
  },
  {
    levelNumber: 29,
    title: "Character Feelings & Emotions",
    description: "Identify character emotions and motivations",
    learningObjectives: ["Develop social-emotional literacy", "Infer feelings from text"],
    pedagogicalApproach: "Emotion recognition in narrative context",
    difficulty: "medium",
    estimatedDuration: 13,
    bloomsLevel: "understand",
    contentGuide: "Story with emotional context. Emotion word bank for reference.",
  },
  {
    levelNumber: 30,
    title: "Reading Fluency: Passage Reading",
    description: "Read longer passage with expression and accuracy",
    learningObjectives: ["Achieve reading automaticity", "Demonstrate fluency"],
    pedagogicalApproach: "Repeated reading for fluency",
    difficulty: "hard",
    estimatedDuration: 15,
    bloomsLevel: "apply",
    contentGuide: "100-150 word passage. Measure accuracy and speed.",
  },

  // PHASE 4: Advanced Reading & Writing (Levels 31-40)
  {
    levelNumber: 31,
    title: "Adjectives: Descriptive Words",
    description: "Understand adjectives and descriptive language",
    learningObjectives: ["Identify adjectives", "Enhance vocabulary sophistication"],
    pedagogicalApproach: "Part-of-speech instruction with examples",
    difficulty: "medium",
    estimatedDuration: 12,
    bloomsLevel: "understand",
    contentGuide: "Highlight descriptive words in sentences. Find synonyms.",
  },
  {
    levelNumber: 32,
    title: "Plural & Possessive Forms",
    description: "Learn singular/plural and possession markers",
    learningObjectives: ["Master morphology rules", "Recognize grammatical markers"],
    pedagogicalApproach: "Rule-based morphological instruction",
    difficulty: "medium",
    estimatedDuration: 12,
    bloomsLevel: "understand",
    contentGuide: "Plurals: regular (cat→cats), irregular (child→children)",
  },
  {
    levelNumber: 33,
    title: "Contractions & Abbreviations",
    description: "Recognize and use contractions (can't, don't)",
    learningObjectives: ["Understand contraction patterns", "Recognize common abbreviations"],
    pedagogicalApproach: "Pattern recognition with expansion practice",
    difficulty: "medium",
    estimatedDuration: 11,
    bloomsLevel: "understand",
    contentGuide: "Shows: will→will not vs. I'll. Common abbreviations like Mr., Dr.",
  },
  {
    levelNumber: 34,
    title: "Cause and Effect",
    description: "Identify causal relationships in text",
    learningObjectives: ["Understand cause-effect relationships", "Build analytical thinking"],
    pedagogicalApproach: "Explicit relationship instruction with visual aids",
    difficulty: "hard",
    estimatedDuration: 14,
    bloomsLevel: "analyze",
    contentGuide: "Sentences showing explicit causation: 'Because it rained, the game was cancelled.'",
  },
  {
    levelNumber: 35,
    title: "Synonyms & Antonyms",
    description: "Identify words with similar and opposite meanings",
    learningObjectives: ["Expand semantic relationships", "Refine vocabulary"],
    pedagogicalApproach: "Semantic relationship mapping",
    difficulty: "medium",
    estimatedDuration: 12,
    bloomsLevel: "understand",
    contentGuide: "Synonym pairs and antonym pairs. Dictionary reinforcement.",
  },
  {
    levelNumber: 36,
    title: "Simple Writing: Copy Sentences",
    description: "Copy and write simple sentences with model",
    learningObjectives: ["Develop fine motor writing skills", "Model writing conventions"],
    pedagogicalApproach: "Modeled writing with physical/typing practice",
    difficulty: "medium",
    estimatedDuration: 15,
    bloomsLevel: "apply",
    contentGuide: "Provide model sentence. Practice with draw/typing options.",
  },
  {
    levelNumber: 37,
    title: "Simple Writing: Sentence Creation",
    description: "Write simple sentences using word bank",
    learningObjectives: ["Apply sentence structure knowledge", "Begin independent writing"],
    pedagogicalApproach: "Scaffolded writing with word bank support",
    difficulty: "hard",
    estimatedDuration: 16,
    bloomsLevel: "apply",
    contentGuide: "Provide: subject bank, verb bank, object bank. Combine to make sentences.",
  },
  {
    levelNumber: 38,
    title: "Compound Sentences: And/But/Or",
    description: "Understand coordinate conjunctions",
    learningObjectives: ["Combine simple sentences", "Understand conjunction function"],
    pedagogicalApproach: "Conjunction instruction with sentence combining",
    difficulty: "hard",
    estimatedDuration: 14,
    bloomsLevel: "understand",
    contentGuide: "Show pairing: 2 simple sentences → 1 compound with and/but/or",
  },
  {
    levelNumber: 39,
    title: "Punctuation: Period, Question, Exclamation",
    description: "Use correct ending punctuation",
    learningObjectives: ["Apply punctuation rules correctly", "Match punctuation to intent"],
    pedagogicalApproach: "Explicit punctuation instruction with speech-to-mark connection",
    difficulty: "medium",
    estimatedDuration: 12,
    bloomsLevel: "apply",
    contentGuide: "Connect tone of voice to punctuation. Choice activities.",
  },
  {
    levelNumber: 40,
    title: "Text Summary: Main Idea",
    description: "Identify main idea and summarize passage",
    learningObjectives: ["Extract key information", "Synthesize text meaning"],
    pedagogicalApproach: "Scaffolded summarization strategy",
    difficulty: "hard",
    estimatedDuration: 15,
    bloomsLevel: "analyze",
    contentGuide: "Provide 150-200 word passage. Answer: What is this about? Why?",
  },

  // PHASE 5: Complex Reading & Writing (Levels 41-50)
  {
    levelNumber: 41,
    title: "Story Elements: Setting, Characters, Plot",
    description: "Identify and analyze complete story elements",
    learningObjectives: ["Understand narrative elements", "Organize story information"],
    pedagogicalApproach: "Narrative analysis framework",
    difficulty: "hard",
    estimatedDuration: 15,
    bloomsLevel: "analyze",
    contentGuide: "Complete story (300+ words). Fill graphic organizer.",
  },
  {
    levelNumber: 42,
    title: "Fact vs. Opinion",
    description: "Distinguish factual statements from opinions",
    learningObjectives: ["Develop critical thinking", "Understand evidence vs. belief"],
    pedagogicalApproach: "Explicit distinction with examples",
    difficulty: "hard",
    estimatedDuration: 14,
    bloomsLevel: "analyze",
    contentGuide: "Statements to categorize. Explain why each is fact or opinion.",
  },
  {
    levelNumber: 43,
    title: "Written Expression: Descriptive Paragraph",
    description: "Write descriptive paragraph with adjectives",
    learningObjectives: ["Use descriptive language effectively", "Organize ideas in writing"],
    pedagogicalApproach: "Model-based paragraph writing",
    difficulty: "hard",
    estimatedDuration: 18,
    bloomsLevel: "create",
    contentGuide: "Prompt provided. Scaffold with sentence starters and word banks.",
  },
  {
    levelNumber: 44,
    title: "Reading Comprehension: Complex Inference",
    description: "Make inferences using multiple text clues",
    learningObjectives: ["Integrate multiple ideas", "Develop deeper comprehension"],
    pedagogicalApproach: "Multi-clue inference strategy",
    difficulty: "hard",
    estimatedDuration: 16,
    bloomsLevel: "evaluate",
    contentGuide: "Questions require synthesis of multiple sentence clues.",
  },
  {
    levelNumber: 45,
    title: "Theme & Message: What Does It Mean?",
    description: "Identify theme and understand author message",
    learningObjectives: ["Understand abstract meaning", "Connect to personal experience"],
    pedagogicalApproach: "Theme identification with discussion",
    difficulty: "hard",
    estimatedDuration: 15,
    bloomsLevel: "evaluate",
    contentGuide: "Thematic text (400+ words). Questions probe deeper meaning.",
  },
  {
    levelNumber: 46,
    title: "Compare and Contrast: Two Stories",
    description: "Compare/contrast literary elements",
    learningObjectives: ["Understand comparative analysis", "See relationships"],
    pedagogicalApproach: "Venn diagram comparison strategy",
    difficulty: "hard",
    estimatedDuration: 16,
    bloomsLevel: "analyze",
    contentGuide: "Two short stories (250 words each). Use Venn diagram or chart.",
  },
  {
    levelNumber: 47,
    title: "Written Expression: Story Creation",
    description: "Write original story with beginning-middle-end",
    learningObjectives: ["Create original narrative", "Apply all writing skills"],
    pedagogicalApproach: "Story planning to writing with graphic organizer",
    difficulty: "hard",
    estimatedDuration: 20,
    bloomsLevel: "create",
    contentGuide: "Story prompt. Plan with organizer. Write 200+ words.",
  },
  {
    levelNumber: 48,
    title: "Dialogue & Quotation Marks",
    description: "Use quotation marks correctly in dialogue",
    learningObjectives: ["Master dialogue conventions", "Apply punctuation rules"],
    pedagogicalApproach: "Dialogue rule instruction with practice",
    difficulty: "hard",
    estimatedDuration: 13,
    bloomsLevel: "apply",
    contentGuide: "'She said, \"Hello.\"' Pattern. Write dialogue with quotations.",
  },
  {
    levelNumber: 49,
    title: "Author's Purpose: Inform, Entertain, Persuade",
    description: "Identify author's primary purpose",
    learningObjectives: ["Understand communicative intent", "Analyze writing choices"],
    pedagogicalApproach: "Purpose identification with evidence",
    difficulty: "hard",
    estimatedDuration: 15,
    bloomsLevel: "evaluate",
    contentGuide: "Three different texts (different genres). Identify purpose for each.",
  },
  {
    levelNumber: 50,
    title: "Advanced Reading & Writing Mastery",
    description: "Comprehensive assessment of all reading/writing skills",
    learningObjectives: [
      "Demonstrate reading fluency",
      "Show comprehension depth",
      "Write effectively",
      "Apply critical thinking",
    ],
    pedagogicalApproach: "Integrated reading-writing performance task",
    difficulty: "hard",
    estimatedDuration: 25,
    bloomsLevel: "create",
    contentGuide: "Read passage (500+ words). Answer comprehension questions. Write response.",
  },
];

/**
 * MATHEMATICS DOMAIN - 50 Levels
 * Progression: Number sense → Basic operations → Extended operations → Problem solving
 * Aligned with: Singapore Math, Van de Walle, Common Core standards
 */
export const MathematicsLevels: LevelDefinition[] = [
  // PHASE 1: Number Sense (Levels 1-10)
  {
    levelNumber: 1,
    title: "Counting: 1-5",
    description: "Basic counting and number identification 1-5",
    learningObjectives: ["Recognize numbers 1-5", "Count with one-to-one correspondence"],
    pedagogicalApproach: "Multisensory counting with visual representations",
    difficulty: "easy",
    estimatedDuration: 5,
    bloomsLevel: "remember",
    contentGuide: "Use consistent visuals (dots, fingers, objects). Audio pronunciation.",
  },
  {
    levelNumber: 2,
    title: "Counting: 1-10",
    description: "Extend counting and number recognition to 10",
    learningObjectives: ["Master numbers 1-10", "Build counting automaticity"],
    pedagogicalApproach: "Systematic counting with ten-frame introduction",
    difficulty: "easy",
    estimatedDuration: 6,
    bloomsLevel: "remember",
    contentGuide: "Introduce ten-frame to show grouping. 10 as important milestone.",
  },
  {
    levelNumber: 3,
    title: "Number Recognition: 0-10",
    description: "Recognize number symbols and their quantities",
    learningObjectives: ["Connect numeral symbol to quantity", "Understand zero"],
    pedagogicalApproach: "Numeral-quantity matching",
    difficulty: "easy",
    estimatedDuration: 6,
    bloomsLevel: "understand",
    contentGuide: "Match numeral card to quantity. Include zero explicitly.",
  },
  {
    levelNumber: 4,
    title: "Counting to 20",
    description: "Count and recognize numbers 11-20",
    learningObjectives: ["Extend counting sequence", "Understand teen numbers"],
    pedagogicalApproach: "Base-10 understanding foundation",
    difficulty: "easy",
    estimatedDuration: 7,
    bloomsLevel: "remember",
    contentGuide: "Show teens as '10 + ones'. Visual ten-frame groupings.",
  },
  {
    levelNumber: 5,
    title: "Subitizing: Quick Number Recognition",
    description: "Instantly recognize small quantities (1-5) without counting",
    learningObjectives: ["Develop number sense", "Build automaticity with small groups"],
    pedagogicalApproach: "Flash card-style subitizing practice",
    difficulty: "medium",
    estimatedDuration: 8,
    bloomsLevel: "remember",
    contentGuide: "Flash arrangements 1-5. Emphasize pattern recognition over counting.",
  },
  {
    levelNumber: 6,
    title: "Comparing Numbers: Greater/Less/Equal",
    description: "Compare two quantities and use comparison symbols",
    learningObjectives: ["Understand magnitude comparison", "Learn comparison symbols"],
    pedagogicalApproach: "Visual comparison with symbol introduction",
    difficulty: "medium",
    estimatedDuration: 8,
    bloomsLevel: "understand",
    contentGuide: "Use: >, <, = symbols. Alligator mouth metaphor for > and <.",
  },
  {
    levelNumber: 7,
    title: "Ordering Numbers: Smallest to Largest",
    description: "Arrange 3-4 numbers in ascending/descending order",
    learningObjectives: ["Understand number sequence", "Build number line sense"],
    pedagogicalApproach: "Sequential ordering with visual number line",
    difficulty: "medium",
    estimatedDuration: 8,
    bloomsLevel: "understand",
    contentGuide: "Use number line visual. Show ascending and descending patterns.",
  },
  {
    levelNumber: 8,
    title: "Tens and Ones: Place Value Introduction",
    description: "Understand numbers as groups of tens and ones",
    learningObjectives: ["Build place value foundation", "Understand grouping"],
    pedagogicalApproach: "Base-10 block manipulation and representation",
    difficulty: "medium",
    estimatedDuration: 10,
    bloomsLevel: "understand",
    contentGuide: "Use tens rods and ones cubes visual. Show decomposition.",
  },
  {
    levelNumber: 9,
    title: "Skip Counting: 2s, 5s, 10s",
    description: "Count by 2s, 5s, and 10s for pattern foundation",
    learningObjectives: ["Develop multiplication readiness", "Build skip-counting automaticity"],
    pedagogicalApproach: "Pattern-based counting with musical rhythm",
    difficulty: "medium",
    estimatedDuration: 10,
    bloomsLevel: "understand",
    contentGuide: "Audio pattern support. Visual number line highlighting pattern.",
  },
  {
    levelNumber: 10,
    title: "Number Sense Mastery: 0-20",
    description: "Comprehensive review of numbers 0-20",
    learningObjectives: ["Master all foundational number concepts", "Achieve automaticity"],
    pedagogicalApproach: "Gamified review of counting, comparison, place value",
    difficulty: "hard",
    estimatedDuration: 12,
    bloomsLevel: "apply",
    contentGuide: "Mixed activities: counting, comparison, place value, ordering.",
  },

  // PHASE 2: Addition (Levels 11-20)
  {
    levelNumber: 11,
    title: "Addition Concept: Putting Together",
    description: "Understand addition as combining quantities",
    learningObjectives: ["Understand addition semantics", "Develop addition mentally"],
    pedagogicalApproach: "Concrete manipulation (objects) → pictorial → abstract",
    difficulty: "medium",
    estimatedDuration: 10,
    bloomsLevel: "understand",
    contentGuide: "Show: 2 objects + 3 objects = 5 objects. Symbolic: 2 + 3 = 5.",
  },
  {
    levelNumber: 12,
    title: "Addition Facts: +1, +2 to 10",
    description: "Master addition facts with sums to 10 (+1, +2)",
    learningObjectives: ["Build addition fluency", "Develop mental strategies"],
    pedagogicalApproach: "Counting-on strategy development",
    difficulty: "medium",
    estimatedDuration: 10,
    bloomsLevel: "remember",
    contentGuide: "Start at larger number, count on. Flash card practice. Finger dot method.",
  },
  {
    levelNumber: 13,
    title: "Addition Facts: +3, +4, +5 to 10",
    description: "Addition facts with larger addends",
    learningObjectives: ["Extend mental addition strategies", "Build automaticity"],
    pedagogicalApproach: "Multiple strategy approach (counting-on, doubles, near-doubles)",
    difficulty: "medium",
    estimatedDuration: 11,
    bloomsLevel: "remember",
    contentGuide: "Show commutative property: 3 + 7 = 7 + 3. Use tens-frame.",
  },
  {
    levelNumber: 14,
    title: "Doubles & Near-Doubles (2+2, 3+3, etc.)",
    description: "Master double and near-double facts",
    learningObjectives: ["Use pattern-based addition strategy", "Build fluency"],
    pedagogicalApproach: "Double recognition with visual patterns",
    difficulty: "medium",
    estimatedDuration: 10,
    bloomsLevel: "understand",
    contentGuide: "Dice patterns for doubles. Show: 5+5=10, 5+6=(5+5)+1=11.",
  },
  {
    levelNumber: 15,
    title: "Addition to 10: All Facts Fluency",
    description: "Master all addition facts with sums to 10",
    learningObjectives: ["Achieve fact automaticity", "Build confidence"],
    pedagogicalApproach: "Systematic review with multiple representations",
    difficulty: "hard",
    estimatedDuration: 12,
    bloomsLevel: "remember",
    contentGuide: "Speed drills (1 minute, 10+ correct). Visual supports gradually removed.",
  },
  {
    levelNumber: 16,
    title: "Addition to 20: Teen Numbers",
    description: "Add with numbers to 20 (including teen numbers)",
    learningObjectives: ["Extend addition to teen numbers", "Use place value strategy"],
    pedagogicalApproach: "Make 10 strategy (decompose to make 10)",
    difficulty: "hard",
    estimatedDuration: 13,
    bloomsLevel: "apply",
    contentGuide: "8 + 5 = (8 + 2) + 3 = 10 + 3 = 13. Show with ten-frame.",
  },
  {
    levelNumber: 17,
    title: "Two-Digit Addition: Regrouping Concepts",
    description: "Add two-digit numbers with regrouping (10s)",
    learningObjectives: ["Understand regrouping mechanism", "Apply place value"],
    pedagogicalApproach: "Base-10 blocks with regrouping demonstration",
    difficulty: "hard",
    estimatedDuration: 14,
    bloomsLevel: "understand",
    contentGuide: "Example: 14 + 8 = (10 + 4) + 8 = 10 + (4 + 8) = 10 + 12 = 22",
  },
  {
    levelNumber: 18,
    title: "Two-Digit Addition: Standard Algorithm",
    description: "Add using traditional column algorithm",
    learningObjectives: ["Apply standard addition algorithm", "Solve multi-digit problems"],
    pedagogicalApproach: "Algorithm development from concrete understanding",
    difficulty: "hard",
    estimatedDuration: 14,
    bloomsLevel: "apply",
    contentGuide: "Show alignment, regrouping notation. Practice without regrouping first.",
  },
  {
    levelNumber: 19,
    title: "Three-Digit Addition: Building Complexity",
    description: "Add three-digit numbers with regrouping",
    learningObjectives: ["Extend algorithm to hundreds", "Maintain accuracy"],
    pedagogicalApproach: "Same algorithm with expanded place value",
    difficulty: "hard",
    estimatedDuration: 15,
    bloomsLevel: "apply",
    contentGuide: "Place value emphasis: hundreds + tens + ones. Step-by-step display.",
  },
  {
    levelNumber: 20,
    title: "Addition Mastery: All Levels of Complexity",
    description: "Comprehensive addition fluency (single to three-digit)",
    learningObjectives: ["Master addition at all levels", "Solve varied problems"],
    pedagogicalApproach: "Mixed practice with varied problem types",
    difficulty: "hard",
    estimatedDuration: 15,
    bloomsLevel: "apply",
    contentGuide: "Single-digit, two-digit, three-digit addition. Word problems included.",
  },

  // PHASE 3: Subtraction (Levels 21-30)
  {
    levelNumber: 21,
    title: "Subtraction Concept: Taking Away",
    description: "Understand subtraction as removing quantities",
    learningObjectives: ["Understand subtraction semantics", "Build mental models"],
    pedagogicalApproach: "Concrete removal with pictorial representation",
    difficulty: "medium",
    estimatedDuration: 10,
    bloomsLevel: "understand",
    contentGuide: "Show removal: 5 objects - 2 objects = 3 objects. Symbolic: 5 - 2 = 3.",
  },
  {
    levelNumber: 22,
    title: "Subtraction Facts: -1, -2 from 10",
    description: "Basic subtraction facts with small differences",
    learningObjectives: ["Build subtraction fluency", "Develop mental strategies"],
    pedagogicalApproach: "Counting back strategy with support",
    difficulty: "medium",
    estimatedDuration: 10,
    bloomsLevel: "remember",
    contentGuide: "Count back from number. Show on number line. Use fingers.",
  },
  {
    levelNumber: 23,
    title: "Subtraction Facts: -3, -4, -5 from 10",
    description: "Extend subtraction fact fluency",
    learningObjectives: ["Build automaticity", "Use multiple strategies"],
    pedagogicalApproach: "Relationship to addition (inverse operation)",
    difficulty: "medium",
    estimatedDuration: 11,
    bloomsLevel: "remember",
    contentGuide: "Connect: 7 - 3 = 4 because 3 + 4 = 7. Use fact families.",
  },
  {
    levelNumber: 24,
    title: "Fact Families: Addition-Subtraction",
    description: "Understand fact family relationships",
    learningObjectives: ["Understand inverse operations", "See number relationships"],
    pedagogicalApproach: "Fact family exploration",
    difficulty: "medium",
    estimatedDuration: 11,
    bloomsLevel: "understand",
    contentGuide: "Family: 3 + 4 = 7, 4 + 3 = 7, 7 - 3 = 4, 7 - 4 = 3",
  },
  {
    levelNumber: 25,
    title: "Subtraction from 10: All Facts Fluency",
    description: "Master all subtraction facts to 10",
    learningObjectives: ["Achieve fact fluency", "Build confidence"],
    pedagogicalApproach: "Timed fluency practice",
    difficulty: "hard",
    estimatedDuration: 12,
    bloomsLevel: "remember",
    contentGuide: "Speed drills (1 minute). Visual supports gradually reduced.",
  },
  {
    levelNumber: 26,
    title: "Subtraction to 20: Teen Numbers",
    description: "Subtract with teen numbers (10-20)",
    learningObjectives: ["Extend subtraction into tens", "Use place value"],
    pedagogicalApproach: "TechniqueFluency development for teens",
    difficulty: "hard",
    estimatedDuration: 13,
    bloomsLevel: "apply",
    contentGuide: "15 - 7 strategies: count back, break apart, use ten-frame.",
  },
  {
    levelNumber: 27,
    title: "Two-Digit Subtraction: No Regrouping",
    description: "Subtract two-digit numbers without regrouping",
    learningObjectives: ["Apply subtraction algorithm", "Use place value"],
    pedagogicalApproach: "Column subtraction from left to right",
    difficulty: "hard",
    estimatedDuration: 13,
    bloomsLevel: "apply",
    contentGuide: "Example: 45 - 23 (no regrouping). Use base-10 blocks initially.",
  },
  {
    levelNumber: 28,
    title: "Two-Digit Subtraction: Regrouping (Borrowing)",
    description: "Subtract with regrouping from tens",
    learningObjectives: ["Understand regrouping in subtraction", "Apply algorithm"],
    pedagogicalApproach: "Explicit regrouping instruction",
    difficulty: "hard",
    estimatedDuration: 15,
    bloomsLevel: "apply",
    contentGuide: "45 - 18: regroup 45 as 3 tens + 15 ones. Use visual step-by-step.",
  },
  {
    levelNumber: 29,
    title: "Three-Digit Subtraction: With Regrouping",
    description: "Subtract three-digit numbers with regrouping",
    learningObjectives: ["Extend algorithm to hundreds", "Maintain accuracy"],
    pedagogicalApproach: "Multiple regrouping scenarios",
    difficulty: "hard",
    estimatedDuration: 15,
    bloomsLevel: "apply",
    contentGuide: "Complex regrouping: hundreds→tens and tens→ones.",
  },
  {
    levelNumber: 30,
    title: "Subtraction Mastery: All Levels",
    description: "Comprehensive subtraction at all complexity levels",
    learningObjectives: ["Master subtraction", "Solve varied problems"],
    pedagogicalApproach: "Mixed practice with word problems",
    difficulty: "hard",
    estimatedDuration: 16,
    bloomsLevel: "apply",
    contentGuide: "Single-digit, two-digit, three-digit. Word problems. Check with addition.",
  },

  // PHASE 4: Multiplication (Levels 31-40)
  {
    levelNumber: 31,
    title: "Multiplication Concept: Groups of",
    description: "Understand multiplication as equal groups",
    learningObjectives: ["Build multiplication mental model", "See arrays"],
    pedagogicalApproach: "Concrete groups with pictorial representation",
    difficulty: "medium",
    estimatedDuration: 12,
    bloomsLevel: "understand",
    contentGuide: "Show: 3 groups of 4 = 12. Array model: ◯◯◯◯ × 3 rows = 12",
  },
  {
    levelNumber: 32,
    title: "Repeated Addition as Multiplication",
    description: "Connect repeated addition to multiplication",
    learningObjectives: ["Understand multiplication-addition relationship"],
    pedagogicalApproach: "Translation between addition and multiplication",
    difficulty: "medium",
    estimatedDuration: 11,
    bloomsLevel: "understand",
    contentGuide: "4 + 4 + 4 = 3 × 4 = 12. Show with objects and numbers.",
  },
  {
    levelNumber: 33,
    title: "Skip Counting: Multiplication Foundation",
    description: "Use skip counting strategy for multiplication",
    learningObjectives: ["Develop skip-counting fluency", "Build multiplication sense"],
    pedagogicalApproach: "Musical rhythm-based skip counting",
    difficulty: "medium",
    estimatedDuration: 11,
    bloomsLevel: "understand",
    contentGuide: "Skip count by 2, 5, 10. Use number line. Auditory support.",
  },
  {
    levelNumber: 34,
    title: "Multiplication Facts: ×2, ×5, ×10",
    description: "Master multiplication facts for 2, 5, 10",
    learningObjectives: ["Build initial multiplication fluency"],
    pedagogicalApproach: "Pattern-based fluency (easy factors)",
    difficulty: "medium",
    estimatedDuration: 12,
    bloomsLevel: "remember",
    contentGuide: "2× and 10× are patterns. 5× ends in 5 or 0. Array visuals.",
  },
  {
    levelNumber: 35,
    title: "Multiplication Facts: ×1, ×3, ×4",
    description: "Extend multiplication facts",
    learningObjectives: ["Expand fact fluency", "Build automaticity"],
    pedagogicalApproach: "Combination of strategies",
    difficulty: "medium",
    estimatedDuration: 12,
    bloomsLevel: "remember",
    contentGuide: "1× is identity. 4× is double-double. 3× is triple.",
  },
  {
    levelNumber: 36,
    title: "Multiplication Facts: ×6, ×7, ×8, ×9",
    description: "Master harder multiplication facts",
    learningObjectives: ["Build complete fact fluency", "Use derivation strategies"],
    pedagogicalApproach: "Derived facts from known facts",
    difficulty: "hard",
    estimatedDuration: 14,
    bloomsLevel: "remember",
    contentGuide: "7×8 = 56: use known facts or fingers. Mnemonic supports.",
  },
  {
    levelNumber: 37,
    title: "Multiplication Facts: All Facts to ×10",
    description: "Fluency with all single-digit multiplication",
    learningObjectives: ["Achieve fact automaticity"],
    pedagogicalApproach: "Timed fluency practice",
    difficulty: "hard",
    estimatedDuration: 13,
    bloomsLevel: "remember",
    contentGuide: "Commutative property exploration. Speed drills.",
  },
  {
    levelNumber: 38,
    title: "Multi-Digit Multiplication: Two-Digit × One-Digit",
    description: "Multiply two-digit numbers by single digits",
    learningObjectives: ["Apply multiplication algorithm"],
    pedagogicalApproach: "Area model to standard algorithm",
    difficulty: "hard",
    estimatedDuration: 15,
    bloomsLevel: "apply",
    contentGuide: "23 × 4 = (20 × 4) + (3 × 4) = 80 + 12 = 92",
  },
  {
    levelNumber: 39,
    title: "Multi-Digit Multiplication: Two-Digit × Two-Digit",
    description: "Multiply two larger numbers",
    learningObjectives: ["Master complex multiplication"],
    pedagogicalApproach: "Standard algorithm with step-by-step",
    difficulty: "hard",
    estimatedDuration: 16,
    bloomsLevel: "apply",
    contentGuide: "23 × 15: multiply tens, ones, add. Show place value columns.",
  },
  {
    levelNumber: 40,
    title: "Multiplication Mastery: All Levels",
    description: "Comprehensive multiplication practice",
    learningObjectives: ["Master multiplication at all levels"],
    pedagogicalApproach: "Mixed practice with word problems",
    difficulty: "hard",
    estimatedDuration: 16,
    bloomsLevel: "apply",
    contentGuide: "Facts, single-digit multiplier, multi-digit. Word problems.",
  },

  // PHASE 5: Division & Mixed Operations (Levels 41-50)
  {
    levelNumber: 41,
    title: "Division Concept: Making Groups",
    description: "Understand division as making equal groups",
    learningObjectives: ["Build division mental model", "See sharing"],
    pedagogicalApproach: "Concrete grouping and sharing",
    difficulty: "medium",
    estimatedDuration: 12,
    bloomsLevel: "understand",
    contentGuide: "12 ÷ 3 = 4: 12 objects in 3 equal groups. Row ÷ columns.",
  },
  {
    levelNumber: 42,
    title: "Division Concept: Sharing",
    description: "Understand division as fair sharing",
    learningObjectives: ["Alternative division perspective", "Distribution understanding"],
    pedagogicalApproach: "Sharing scenarios with objects",
    difficulty: "medium",
    estimatedDuration: 12,
    bloomsLevel: "understand",
    contentGuide: "12 objects shared among 3 people: each gets 4. Real-world context.",
  },
  {
    levelNumber: 43,
    title: "Relationship: Multiplication-Division",
    description: "Understand division as inverse of multiplication",
    learningObjectives: ["See inverse relationship"],
    pedagogicalApproach: "Fact family approach",
    difficulty: "medium",
    estimatedDuration: 11,
    bloomsLevel: "understand",
    contentGuide: "3 × 4 = 12, so 12 ÷ 3 = 4 and 12 ÷ 4 = 3.",
  },
  {
    levelNumber: 44,
    title: "Division Facts: ÷2, ÷5, ÷10",
    description: "Basic division facts with easy divisors",
    learningObjectives: ["Build division fluency", "Use multiplication knowledge"],
    pedagogicalApproach: "Inverse operation approach",
    difficulty: "medium",
    estimatedDuration: 12,
    bloomsLevel: "remember",
    contentGuide: "If 2 × ? = 10, then 10 ÷ 2 = 5. Use related multiplication facts.",
  },
  {
    levelNumber: 45,
    title: "Division Facts: ÷3, ÷4, ÷6, ÷7, ÷8, ÷9",
    description: "Complete division facts mastery",
    learningObjectives: ["Achieve fact fluency"],
    pedagogicalApproach: "Speed practice with strategy support",
    difficulty: "hard",
    estimatedDuration: 13,
    bloomsLevel: "remember",
    contentGuide: "Timed fluency. Number line jumping approach initially.",
  },
  {
    levelNumber: 46,
    title: "Division with Remainders",
    description: "Divide with remainders (understanding the remainder)",
    learningObjectives: ["Understand remainders in context"],
    pedagogicalApproach: "Remainder in real-world context",
    difficulty: "hard",
    estimatedDuration: 13,
    bloomsLevel: "understand",
    contentGuide: "13 ÷ 3: 3 groups of 4 with 1 remaining. Interpret remainder.",
  },
  {
    levelNumber: 47,
    title: "Long Division: Single-Digit Divisor",
    description: "Standard long division algorithm",
    learningObjectives: ["Apply long division algorithm"],
    pedagogicalApproach: "Algorithm development with place value",
    difficulty: "hard",
    estimatedDuration: 15,
    bloomsLevel: "apply",
    contentGuide: "Divide, multiply, subtract, bring down. Step-by-step notation.",
  },
  {
    levelNumber: 48,
    title: "Mixed Operations: Order (PEMDAS/BODMAS)",
    description: "Solve problems with multiple operations",
    learningObjectives: ["Apply order of operations", "Solve complex problems"],
    pedagogicalApproach: "Explicit order instruction with memory device",
    difficulty: "hard",
    estimatedDuration: 14,
    bloomsLevel: "apply",
    contentGuide: "2 + 3 × 4 = 14, not 20. Parentheses first, then multiply/divide.",
  },
  {
    levelNumber: 49,
    title: "Problem-Solving: Multi-Step Word Problems",
    description: "Solve complex word problems requiring multiple steps",
    learningObjectives: ["Apply all operations in context", "Develop problem-solving strategies"],
    pedagogicalApproach: "Problem-solving framework (CUBES or similar)",
    difficulty: "hard",
    estimatedDuration: 16,
    bloomsLevel: "analyze",
    contentGuide: "Real-world scenarios. Show: Circle numbers, Underline question, Box operation.",
  },
  {
    levelNumber: 50,
    title: "Mathematics Mastery: Comprehensive",
    description: "Advanced problem-solving with all operations",
    learningObjectives: [
      "Master all arithmetic operations",
      "Develop mathematical reasoning",
      "Solve novel problems",
    ],
    pedagogicalApproach: "Complex word problems and patterns",
    difficulty: "hard",
    estimatedDuration: 20,
    bloomsLevel: "evaluate",
    contentGuide: "Multi-step problems, patterns, logic puzzles integrated with operations.",
  },
];

/**
 * LOGICAL DOMAIN - 50 Levels
 * Progression: Pattern recognition → Sequences → Spatial reasoning → Complex logic
 * Aligned with: Raven's Progressive Matrices, IQ testing theory
 */
export const LogicalLevels: LevelDefinition[] = [
  // PHASE 1: Basic Pattern Recognition (Levels 1-10)
  {
    levelNumber: 1,
    title: "Visual Patterns: Color Sequence",
    description: "Recognize and continue simple color patterns",
    learningObjectives: ["Identify visual patterns", "Develop pattern recognition"],
    pedagogicalApproach: "AB pattern recognition",
    difficulty: "easy",
    estimatedDuration: 6,
    bloomsLevel: "remember",
    contentGuide: "Red-Blue-Red-Blue-Red-? Patterns: AB, AAB, ABC progressions.",
  },
  {
    levelNumber: 2,
    title: "Shape Patterns",
    description: "Recognize patterns in geometric shapes",
    learningObjectives: ["Identify shape sequences", "Visual discrimination"],
    pedagogicalApproach: "Shape rotation and progression",
    difficulty: "easy",
    estimatedDuration: 6,
    bloomsLevel: "remember",
    contentGuide: "Circle-Square-Triangle-Circle-Square-Triangle-?",
  },
  {
    levelNumber: 3,
    title: "Size Patterns",
    description: "Recognize patterns in object size",
    learningObjectives: ["Understand magnitude progression"],
    pedagogicalApproach: "Size ordering and sequences",
    difficulty: "easy",
    estimatedDuration: 6,
    bloomsLevel: "remember",
    contentGuide: "Small-Medium-Large-Small-Medium-Large-?",
  },
  {
    levelNumber: 4,
    title: "Number Patterns: Counting",
    description: "Continue numerical counting sequences",
    learningObjectives: ["Recognize arithmetic sequences"],
    pedagogicalApproach: "Number sequence extension",
    difficulty: "easy",
    estimatedDuration: 7,
    bloomsLevel: "understand",
    contentGuide: "2-4-6-8-10-? (count by 2). Simple increments.",
  },
  {
    levelNumber: 5,
    title: "Mixed Patterns: Color + Shape",
    description: "Identify patterns with two variable dimensions",
    learningObjectives: ["Analyze multi-dimensional patterns"],
    pedagogicalApproach: "Complex pattern recognition",
    difficulty: "easy",
    estimatedDuration: 7,
    bloomsLevel: "understand",
    contentGuide: "Red-Circle, Blue-Square pattern combinations.",
  },
  {
    levelNumber: 6,
    title: "Alternating Patterns: ABAB",
    description: "Recognize and extend alternating patterns",
    learningObjectives: ["Understand period-2 patterns"],
    pedagogicalApproach: "Alternation principle",
    difficulty: "medium",
    estimatedDuration: 7,
    bloomsLevel: "understand",
    contentGuide: "On-Off, Yes-No, Big-Small alternations.",
  },
  {
    levelNumber: 7,
    title: "Growing Patterns: Additions",
    description: "Recognize patterns with growing quantities",
    learningObjectives: ["Understand addition-based patterns"],
    pedagogicalApproach: "Cumulative growth recognition",
    difficulty: "medium",
    estimatedDuration: 8,
    bloomsLevel: "understand",
    contentGuide: "1 dot, 2 dots, 3 dots, 4 dots. 1, 1+2, 1+2+3 pattern.",
  },
  {
    levelNumber: 8,
    title: "Repeating Patterns: AAB, ABC",
    description: "Identify more complex repeating patterns",
    learningObjectives: ["Recognize complex periodicities"],
    pedagogicalApproach: "Pattern period identification",
    difficulty: "medium",
    estimatedDuration: 8,
    bloomsLevel: "understand",
    contentGuide: "Red-Red-Blue repetition (AAB), or ABC patterns.",
  },
  {
    levelNumber: 9,
    title: "Matrix Patterns: 3×3 grid (Basic)",
    description: "Complete simple 3×3 pattern matrix",
    learningObjectives: ["Analyze grid-based patterns"],
    pedagogicalApproach: "Row and column analysis",
    difficulty: "medium",
    estimatedDuration: 9,
    bloomsLevel: "analyze",
    contentGuide: "Rows or columns follow pattern. Find missing cell.",
  },
  {
    levelNumber: 10,
    title: "Pattern Mastery: All Types",
    description: "Comprehensive pattern recognition",
    learningObjectives: ["Master pattern recognition", "Apply flexibly"],
    pedagogicalApproach: "Mixed pattern types",
    difficulty: "hard",
    estimatedDuration: 11,
    bloomsLevel: "analyze",
    contentGuide: "All pattern types from levels 1-9 combined.",
  },

  // PHASE 2: Number Sequences (Levels 11-20)
  {
    levelNumber: 11,
    title: "Arithmetic Sequences: +1, +2, +5",
    description: "Continue sequences with consistent increments",
    learningObjectives: ["Identify arithmetic progressions"],
    pedagogicalApproach: "Difference analysis",
    difficulty: "medium",
    estimatedDuration: 8,
    bloomsLevel: "understand",
    contentGuide: "Find the difference between successive numbers.",
  },
  {
    levelNumber: 12,
    title: "Fibonacci-like Sequences",
    description: "Recognize patterns where each term is sum of previous",
    learningObjectives: ["Understand recursive sequences"],
    pedagogicalApproach: "Additive combination rule discovery",
    difficulty: "hard",
    estimatedDuration: 10,
    bloomsLevel: "analyze",
    contentGuide: "1 1 2 3 5 8 13 ... (each = sum of previous 2)",
  },
  {
    levelNumber: 13,
    title: "Multiplicative Sequences: ×2, ×3",
    description: "Sequences with multiplicative increments",
    learningObjectives: ["Understand geometric progressions"],
    pedagogicalApproach: "Ratio-based analysis",
    difficulty: "hard",
    estimatedDuration: 9,
    bloomsLevel: "understand",
    contentGuide: "1 2 4 8 16 ? (each is double). 2:4:8:16 ratio analysis.",
  },
  {
    levelNumber: 14,
    title: "Decreasing Sequences: Subtraction",
    description: "Continue counting-down patterns",
    learningObjectives: ["Recognize decreasing patterns"],
    pedagogicalApproach: "Negative progression handling",
    difficulty: "medium",
    estimatedDuration: 8,
    bloomsLevel: "understand",
    contentGuide: "10 8 6 4 2 ? or 20 15 10 5 ?",
  },
  {
    levelNumber: 15,
    title: "Complex Sequences: Multiple Rules",
    description: "Sequences with more than one operational rule",
    learningObjectives: ["Identify complex patterns"],
    pedagogicalApproach: "Rule decomposition",
    difficulty: "hard",
    estimatedDuration: 11,
    bloomsLevel: "analyze",
    contentGuide: "Alternating operations: +1, ×2, +1, ×2, alternating increments.",
  },
  {
    levelNumber: 16,
    title: "Missing Term: Arithmetic",
    description: "Find missing number in arithmetic sequence",
    learningObjectives: ["Solve for unknowns in patterns"],
    pedagogicalApproach: "Algebraic thinking foundation",
    difficulty: "hard",
    estimatedDuration: 10,
    bloomsLevel: "apply",
    contentGuide: "2 4 ? 8 10 - find 6. Multiple choice or input answer.",
  },
  {
    levelNumber: 17,
    title: "Analogy Sequences: A:B::C:?",
    description: "Complete proportion-based sequences",
    learningObjectives: ["Understand analogical reasoning"],
    pedagogicalApproach: "Proportion and ratio understanding",
    difficulty: "hard",
    estimatedDuration: 10,
    bloomsLevel: "analyze",
    contentGuide: "2 is to 4 as 3 is to ? (proportional reasoning)",
  },
  {
    levelNumber: 18,
    title: "Digit Patterns: Number Breakdown",
    description: "Patterns based on digits within numbers",
    learningObjectives: ["Analyze digit-level patterns"],
    pedagogicalApproach: "Place value pattern recognition",
    difficulty: "hard",
    estimatedDuration: 11,
    bloomsLevel: "analyze",
    contentGuide: "11 22 33 44 ? or 12 23 34 45 ? (digit progression)",
  },
  {
    levelNumber: 19,
    title: "Palindromic & Special Sequences",
    description: "Mirror patterns and palindromic numbers",
    learningObjectives: ["Recognize symmetry patterns"],
    pedagogicalApproach: "Symmetry principle",
    difficulty: "hard",
    estimatedDuration: 11,
    bloomsLevel: "analyze",
    contentGuide: "121 232 343 454 ? or visual symmetry patterns.",
  },
  {
    levelNumber: 20,
    title: "Sequence Mastery: All Types",
    description: "Comprehensive numerical sequence analysis",
    learningObjectives: ["Master all sequence types"],
    pedagogicalApproach: "Mixed sequence problems",
    difficulty: "hard",
    estimatedDuration: 13,
    bloomsLevel: "analyze",
    contentGuide: "All sequence types from levels 11-19.",
  },

  // PHASE 3: Spatial & Logical Reasoning (Levels 21-35)
  {
    levelNumber: 21,
    title: "Rotations: 90°, 180°, 270°",
    description: "Recognize shape rotations",
    learningObjectives: ["Understand spatial transformations"],
    pedagogicalApproach: "Mental rotation training",
    difficulty: "medium",
    estimatedDuration: 9,
    bloomsLevel: "understand",
    contentGuide: "Shape rotated 90° clockwise - what does it look like?",
  },
  {
    levelNumber: 22,
    title: "Reflections: Mirror Images",
    description: "Identify mirror/reflected images",
    learningObjectives: ["Understand reflection symmetry"],
    pedagogicalApproach: "Mirror line principle",
    difficulty: "medium",
    estimatedDuration: 9,
    bloomsLevel: "understand",
    contentGuide: "Vertical/horizontal flip. Left-right mirror.",
  },
  {
    levelNumber: 23,
    title: "Translations: Sliding",
    description: "Recognize shifted/translated positions",
    learningObjectives: ["Understand spatial displacement"],
    pedagogicalApproach: "Position change recognition",
    difficulty: "medium",
    estimatedDuration: 9,
    bloomsLevel: "understand",
    contentGuide: "Object moved up 2, right 3. New position?",
  },
  {
    levelNumber: 24,
    title: "Shapes: Counting Sides & Angles",
    description: "Identify and classify polygons",
    learningObjectives: ["Recognize geometric properties"],
    pedagogicalApproach: "Attribute-based classification",
    difficulty: "medium",
    estimatedDuration: 8,
    bloomsLevel: "understand",
    contentGuide: "Triangle (3), Square (4), Pentagon (5), etc.",
  },
  {
    levelNumber: 25,
    title: "Shapes: Complex 2D Composition",
    description: "Identify shapes composed of other shapes",
    learningObjectives: ["Understand shape decomposition"],
    pedagogicalApproach: "Part-whole relationships",
    difficulty: "hard",
    estimatedDuration: 10,
    bloomsLevel: "analyze",
    contentGuide: "House = rectangle + triangle. Tangram-like puzzles.",
  },
  {
    levelNumber: 26,
    title: "3D Shapes: Cubes & Nets",
    description: "Understand 3D cube representations and nets",
    learningObjectives: ["Develop 3D spatial reasoning"],
    pedagogicalApproach: "2D-3D transformation",
    difficulty: "hard",
    estimatedDuration: 11,
    bloomsLevel: "apply",
    contentGuide: "Which net folds into a cube? How does cube look from side?",
  },
  {
    levelNumber: 27,
    title: "Line Relationships: Parallel, Perpendicular",
    description: "Recognize geometric line relationships",
    learningObjectives: ["Understand line properties"],
    pedagogicalApproach: "Geometric relationship definition",
    difficulty: "medium",
    estimatedDuration: 9,
    bloomsLevel: "understand",
    contentGuide: "Visual identification: parallel (never meet), perpendicular (90°)",
  },
  {
    levelNumber: 28,
    title: "Coordinate Geometry: Grid Positions",
    description: "Navigate and plot points on coordinate grid",
    learningObjectives: ["Understand coordinate systems"],
    pedagogicalApproach: "Grid-based position encoding",
    difficulty: "hard",
    estimatedDuration: 11,
    bloomsLevel: "apply",
    contentGuide: "(x,y) coordinates. Which position is (3,2)?",
  },
  {
    levelNumber: 29,
    title: "Complex Spatial Puzzles",
    description: "Advanced spatial reasoning tasks",
    learningObjectives: ["Develop advanced spatial skills"],
    pedagogicalApproach: "Puzzle-solving with spatial constraints",
    difficulty: "hard",
    estimatedDuration: 13,
    bloomsLevel: "analyze",
    contentGuide: "Tangram puzzles, Pentomino fitting, visual reasoning tests.",
  },
  {
    levelNumber: 30,
    title: "Logic Puzzles: Basic Deduction",
    description: "Solve simple logic puzzles using elimination",
    learningObjectives: ["Develop logical deduction chains"],
    pedagogicalApproach: "Elimination method training",
    difficulty: "hard",
    estimatedDuration: 12,
    bloomsLevel: "analyze",
    contentGuide: "Who is who? Grid logic puzzle with simple constraints.",
  },

  // PHASE 4: Advanced Logic (Levels 31-40)
  {
    levelNumber: 31,
    title: "Boolean Logic: And, Or, Not",
    description: "Understand logical operations",
    learningObjectives: ["Understand boolean operators"],
    pedagogicalApproach: "Set operations and truth tables",
    difficulty: "hard",
    estimatedDuration: 11,
    bloomsLevel: "understand",
    contentGuide: "If (A AND B) what's true? Set diagrams, truth tables.",
  },
  {
    levelNumber: 32,
    title: "Categorization: Sorting Rules",
    description: "Sort objects by attribute rules",
    learningObjectives: ["Understand categorization logic"],
    pedagogicalApproach: "Rule-based sorting",
    difficulty: "medium",
    estimatedDuration: 10,
    bloomsLevel: "apply",
    contentGuide: "Sort by color AND size, by shape OR color, etc.",
  },
  {
    levelNumber: 33,
    title: "Syllogisms: All, Some, None",
    description: "Complete logical syllogisms",
    learningObjectives: ["Understand formal logical reasoning"],
    pedagogicalApproach: "Classic syllogistic logic",
    difficulty: "hard",
    estimatedDuration: 12,
    bloomsLevel: "analyze",
    contentGuide: "All cats are animals. Fluffy is a cat. Therefore, Fluffy is...?",
  },
  {
    levelNumber: 34,
    title: "Conditional Logic: If-Then",
    description: "Understand conditional statements and implications",
    learningObjectives: ["Reason with conditions"],
    pedagogicalApproach: "Conditional reasoning principles",
    difficulty: "hard",
    estimatedDuration: 12,
    bloomsLevel: "analyze",
    contentGuide: "If it rains, the ground is wet. It's not raining. Is ground wet?",
  },
  {
    levelNumber: 35,
    title: "Family Relations: Relationships",
    description: "Solve family relationship logic puzzles",
    learningObjectives: ["Understand transitive relations"],
    pedagogicalApproach: "Relationship chain reasoning",
    difficulty: "hard",
    estimatedDuration: 13,
    bloomsLevel: "analyze",
    contentGuide: "John's sister's brother's mother is? Complex relations.",
  },
  {
    levelNumber: 36,
    title: "Rebus Puzzles",
    description: "Solve visual word puzzles",
    learningObjectives: ["Develop creative pattern recognition"],
    pedagogicalApproach: "Visual-linguistic solving",
    difficulty: "hard",
    estimatedDuration: 12,
    bloomsLevel: "apply",
    contentGuide: "STAND I = I understand. Creative visual representations.",
  },
  {
    levelNumber: 37,
    title: "Lateral Thinking Puzzles",
    description: "Solve non-linear thinking problems",
    learningObjectives: ["Develop lateral thinking"],
    pedagogicalApproach: "Challenge assumptions",
    difficulty: "hard",
    estimatedDuration: 14,
    bloomsLevel: "analyze",
    contentGuide: "Man in room with no windows - who is outside? Creative solutions.",
  },
  {
    levelNumber: 38,
    title: "Sudoku: Basic 4×4",
    description: "Solve introductory Sudoku puzzles",
    learningObjectives: ["Apply constraint-based logic"],
    pedagogicalApproach: "Deductive grid logic",
    difficulty: "hard",
    estimatedDuration: 13,
    bloomsLevel: "apply",
    contentGuide: "Numbers 1-4 in rows, columns, boxes. Start with guided version.",
  },
  {
    levelNumber: 39,
    title: "Sudoku: Standard 9×9",
    description: "Solve standard Sudoku with numbers 1-9",
    learningObjectives: ["Master complex constraint logic"],
    pedagogicalApproach: "Advanced solving strategies",
    difficulty: "hard",
    estimatedDuration: 20,
    bloomsLevel: "apply",
    contentGuide: "Full Sudoku. Multiple difficulty levels within.",
  },
  {
    levelNumber: 40,
    title: "Advanced Logic Mastery",
    description: "Comprehensive logic puzzle solving",
    learningObjectives: ["Master all logical reasoning types"],
    pedagogicalApproach: "Mixed logic puzzle types",
    difficulty: "hard",
    estimatedDuration: 18,
    bloomsLevel: "evaluate",
    contentGuide: "All logic types from 31-39 combined.",
  },

  // PHASE 5: Expert Puzzle Solving (Levels 41-50)
  {
    levelNumber: 41,
    title: "Matrix Reasoning: Complex 3×3",
    description: "Advanced Ravens-style matrix puzzles",
    learningObjectives: ["Develop abstract reasoning"],
    pedagogicalApproach: "Complex pattern matrix analysis",
    difficulty: "hard",
    estimatedDuration: 14,
    bloomsLevel: "analyze",
    contentGuide: "Multiple pattern dimensions. Raven-style matrices.",
  },
  {
    levelNumber: 42,
    title: "Cryptarithmetic",
    description: "Solve letter-substitution math puzzles",
    learningObjectives: ["Combine logic and mathematics"],
    pedagogicalApproach: "Constraint satisfaction",
    difficulty: "hard",
    estimatedDuration: 15,
    bloomsLevel: "analyze",
    contentGuide: "SEND + MORE = MONEY. Letters = digits, solve for unique digit assignment.",
  },
  {
    levelNumber: 43,
    title: "Logical Deduction: Complex Grid",
    description: "Multi-constraint logic grids",
    learningObjectives: ["Master complex deductive systems"],
    pedagogicalApproach: "Systematic elimination chains",
    difficulty: "hard",
    estimatedDuration: 16,
    bloomsLevel: "analyze",
    contentGuide: "5+ attributes, 5+ options. Complex constraint combinations.",
  },
  {
    levelNumber: 44,
    title: "Tower of Hanoi",
    description: "Solve recursive Tower of Hanoi puzzle",
    learningObjectives: ["Understand algorithmic thinking"],
    pedagogicalApproach: "Recursive problem decomposition",
    difficulty: "hard",
    estimatedDuration: 14,
    bloomsLevel: "apply",
    contentGuide: "Move disks following rules. Optimal solutions required.",
  },
  {
    levelNumber: 45,
    title: "Knight's Tour (Chess Pattern)",
    description: "Navigate knight across chessboard",
    learningObjectives: ["Develop pathfinding algorithms"],
    pedagogicalApproach: "Graph traversal concept",
    difficulty: "hard",
    estimatedDuration: 16,
    bloomsLevel: "apply",
    contentGuide: "Knight moves in L-shape. Visit all squares once.",
  },
  {
    levelNumber: 46,
    title: "Water Pouring: Logic Optimization",
    description: "Solve water jug puzzles",
    learningObjectives: ["Develop problem-solving strategies"],
    pedagogicalApproach: "State-space search",
    difficulty: "hard",
    estimatedDuration: 15,
    bloomsLevel: "apply",
    contentGuide: "3-8 liter containers. Measure exact quantity. Minimum moves.",
  },
  {
    levelNumber: 47,
    title: "Sequence Completion: Expert Level",
    description: "Masters of complex sequence analysis",
    learningObjectives: ["Expert pattern recognition"],
    pedagogicalApproach: "Complex multi-rule patterns",
    difficulty: "hard",
    estimatedDuration: 15,
    bloomsLevel: "evaluate",
    contentGuide: "IQ test-level sequences. Multiple simultaneous patterns.",
  },
  {
    levelNumber: 48,
    title: "Probability & Statistics Logic",
    description: "Logical reasoning with probability",
    learningObjectives: ["Apply probability thinking"],
    pedagogicalApproach: "Bayesian reasoning introduction",
    difficulty: "hard",
    estimatedDuration: 16,
    bloomsLevel: "analyze",
    contentGuide: "Logic puzzles with probabilistic elements. Conditional probability.",
  },
  {
    levelNumber: 49,
    title: "Integration: All Advanced Reasoning",
    description: "Mixed expert-level logic and reasoning",
    learningObjectives: ["Master all advanced logical skills"],
    pedagogicalApproach: "Integrated challenging problems",
    difficulty: "hard",
    estimatedDuration: 18,
    bloomsLevel: "evaluate",
    contentGuide: "Toughest puzzles, highest complexity reasoning required.",
  },
  {
    levelNumber: 50,
    title: "Logic Expert Championship",
    description: "Ultimate reasoning and logic challenge",
    learningObjectives: [
      "Master complex logical reasoning",
      "Solve novel problems",
      "Think critically",
    ],
    pedagogicalApproach: "Expert-level integrated challenge",
    difficulty: "hard",
    estimatedDuration: 25,
    bloomsLevel: "evaluate",
    contentGuide: "Combination of all logic types. IQ/olympiad-level difficulty.",
  },
];

/**
 * Complete level map
 */
export const AllLevelDefinitions: DomainLevelMap = {
  language: LanguageLevels,
  mathematics: MathematicsLevels,
  logical: LogicalLevels,
};

/**
 * Helper: Get level definition
 */
export function getLevelDefinition(domain: string, levelNumber: number): LevelDefinition | null {
  const levels = AllLevelDefinitions[domain as keyof DomainLevelMap];
  if (!levels) return null;
  return levels.find((l) => l.levelNumber === levelNumber) || null;
}
